### ISSUE TITLE
如果我有数据集，可以用您的模型训练一下吗？

### ISSUE THREAD

**Issue by g101400** [LSH9832/edgeyolo#11]
如果我有数据集，可以用您的模型训练一下吗？如何操作
我直接训练，如下错误
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'model_cfg' not list in settings file, use default value: model_cfg=params/model/edgeyolo.yaml
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'weights' not list in settings file, use default value: weights=output/train/edgeyolo_coco/last.pth
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'use_cfg' not list in settings file, use default value: use_cfg=False
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'output_dir' not list in settings file, use default value: output_dir=output/train/edgeyolo_coco
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'save_checkpoint_for_each_epoch' not list in settings file, use default value: save_checkpoint_for_each_epoch=True
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'log_file' not list in settings file, use default value: log_file=log.txt
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'dataset_cfg' not list in settings file, use default value: dataset_cfg=params/dataset/coco.yaml
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'batch_size_per_gpu' not list in settings file, use default value: batch_size_per_gpu=8
2023-02-22 21:08:33.924 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'loader_num_workers' not list in settings file, use default value: loader_num_workers=4
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'num_threads' not list in settings file, use default value: num_threads=1
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'device' not list in settings file, use default value: device=[0, 1, 2, 3]
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'fp16' not list in settings file, use default value: fp16=False
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'cudnn_benchmark' not list in settings file, use default value: cudnn_benchmark=False
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'optimizer' not list in settings file, use default value: optimizer=SGD
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'max_epoch' not list in settings file, use default value: max_epoch=300
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'close_mosaic_epochs' not list in settings file, use default value: close_mosaic_epochs=15
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'lr_per_img' not list in settings file, use default value: lr_per_img=0.00015625
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'warmup_epochs' not list in settings file, use default value: warmup_epochs=5
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'warmup_lr_ratio' not list in settings file, use default value: warmup_lr_ratio=0.0
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'final_lr_ratio' not list in settings file, use default value: final_lr_ratio=0.05
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'loss_use' not list in settings file, use default value: loss_use=['bce', 'bce', 'giou']
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'input_size' not list in settings file, use default value: input_size=[640, 640]
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'multiscale_range' not list in settings file, use default value: multiscale_range=5
2023-02-22 21:08:33.925 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'weight_decay' not list in settings file, use default value: weight_decay=0.0005
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'momentum' not list in settings file, use default value: momentum=0.9
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'enhance_mosaic' not list in settings file, use default value: enhance_mosaic=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'use_ema' not list in settings file, use default value: use_ema=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'enable_mixup' not list in settings file, use default value: enable_mixup=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'mixup_scale' not list in settings file, use default value: mixup_scale=[0.5, 1.5]
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'mosaic_scale' not list in settings file, use default value: mosaic_scale=[0.1, 2.0]
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'flip_prob' not list in settings file, use default value: flip_prob=0.5
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'mosaic_prob' not list in settings file, use default value: mosaic_prob=1
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'mixup_prob' not list in settings file, use default value: mixup_prob=1
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'degrees' not list in settings file, use default value: degrees=10
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'hsv_gain' not list in settings file, use default value: hsv_gain=[0.0138, 0.664, 0.464]
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'eval_at_start' not list in settings file, use default value: eval_at_start=False
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'val_conf_thres' not list in settings file, use default value: val_conf_thres=0.001
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'val_nms_thres' not list in settings file, use default value: val_nms_thres=0.65
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'eval_only' not list in settings file, use default value: eval_only=False
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'obj_conf_enabled' not list in settings file, use default value: obj_conf_enabled=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'eval_interval' not list in settings file, use default value: eval_interval=1
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'print_interval' not list in settings file, use default value: print_interval=100
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'load_optimizer_params' not list in settings file, use default value: load_optimizer_params=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'train_backbone' not list in settings file, use default value: train_backbone=True
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'train_start_layers' not list in settings file, use default value: train_start_layers=51
2023-02-22 21:08:33.926 | INFO     | edgeyolo.train.launch_train:load_train_settings:31 - param 'force_start_epoch' not list in settings file, use default value: force_start_epoch=-1
Traceback (most recent call last):
  File "D:\myworkspace\yolov5\edgeyolo-main\train.py", line 16, in <module>
    train("DEFAULT" if args.default else args.cfg)
  File "D:\myworkspace\yolov5\edgeyolo-main\edgeyolo\train\launch_train.py", line 101, in launch
    mp.start_processes(
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 188, in start_processes
    while not context.join():
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "D:\myworkspace\yolov5\edgeyolo-main\edgeyolo\train\launch_train.py", line 50, in train_single
    torch.cuda.set_device(device)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

**Comment by LSH9832** [comment]
这个错误报的是没有读取到cfg文件的参数，请检查训练的cfg文件（示例在文件夹params/train下）位置是否填写正确

**Comment by LSH9832** [comment]
具体步骤请按照[README](https://github.com/LSH9832/edgeyolo/blob/main/README_CN.md)中的说明进行，目前支持COCO/VOC/DOTA/VisDrone四种数据集格式（示例在params/dataset下），如为其他格式数据集需要进行格式转换
