### ISSUE TITLE
Error in export to TRT int8

### ISSUE THREAD

**Issue by icklerly1** [LSH9832/edgeyolo#13]
Hi,

I have a question regarding the TRT-export with int8.

I do the following command:

`python export.py --trt --weights edgeyolo_visdrone.pth --batch 1 --workspace 8 --int8 --dataset params/dataset/visdrone_coco.yaml --num-imgs 16`

Unfortunately after the calibration part I get the following error.
Do you have any idea or suggestion what I am doing wrong?

Thanks in advance!

```
2023-03-03 12:39:32.768 | INFO     | edgeyolo.models:__init__:50 - loading models from weight /opt/ssd/visiontools/edgeyolo/edgeyolo_visdrone.pth
/opt/ssd/visiontools/edgeyolo/venv/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2311.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Reparameterizing models...
2023-03-03 12:39:37.982 | INFO     | edgeyolo.export.calib:__init__:43 - used images: 16
[03/03/2023-12:39:46] [TRT] [I] [MemUsageChange] Init CUDA: CPU +221, GPU +0, now: CPU 763, GPU 9107 (MiB)
[03/03/2023-12:39:49] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +302, GPU +404, now: CPU 1088, GPU 9512 (MiB)
2023-03-03 12:40:04.763 | INFO     | edgeyolo.export.pth2trt:torch2onnx2trt:137 - start to simplify ONNX...
2023-03-03 12:40:08.507 | INFO     | edgeyolo.export.pth2trt:torch2onnx2trt:140 - simplified ONNX successfully.
[03/03/2023-12:40:08] [TRT] [W] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[03/03/2023-12:40:11] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +535, GPU +539, now: CPU 2739, GPU 11713 (MiB)
[03/03/2023-12:40:11] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +82, GPU +122, now: CPU 2821, GPU 11835 (MiB)
[03/03/2023-12:40:11] [TRT] [I] Timing cache disabled. Turning it on will improve builder speed.
[03/03/2023-12:40:17] [TRT] [I] Total Activation Memory: 9815946752
[03/03/2023-12:40:17] [TRT] [I] Detected 1 inputs and 4 output network tensors.
[03/03/2023-12:40:18] [TRT] [I] Total Host Persistent Memory: 239856
[03/03/2023-12:40:18] [TRT] [I] Total Device Persistent Memory: 0
[03/03/2023-12:40:18] [TRT] [I] Total Scratch Memory: 0
[03/03/2023-12:40:18] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 18 MiB, GPU 384 MiB
[03/03/2023-12:40:18] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 372 steps to complete.
[03/03/2023-12:40:18] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 47.7322ms to assign 10 blocks to 372 nodes requiring 182681600 bytes.
[03/03/2023-12:40:18] [TRT] [I] Total Activation Memory: 182681600
[03/03/2023-12:40:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +3, now: CPU 3143, GPU 12633 (MiB)
[03/03/2023-12:40:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +5, now: CPU 3143, GPU 12618 (MiB)
[03/03/2023-12:40:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +174, now: CPU 0, GPU 430 (MiB)
[03/03/2023-12:40:18] [TRT] [I] Starting Calibration.
[03/03/2023-12:40:20] [TRT] [I]   Calibrated batch 0 in 1.90551 seconds.
[03/03/2023-12:40:22] [TRT] [I]   Calibrated batch 1 in 1.72534 seconds.
[03/03/2023-12:40:24] [TRT] [I]   Calibrated batch 2 in 1.71749 seconds.
[03/03/2023-12:40:25] [TRT] [I]   Calibrated batch 3 in 1.73021 seconds.
[03/03/2023-12:40:27] [TRT] [I]   Calibrated batch 4 in 1.71629 seconds.
[03/03/2023-12:40:29] [TRT] [I]   Calibrated batch 5 in 1.7292 seconds.
[03/03/2023-12:40:31] [TRT] [I]   Calibrated batch 6 in 1.72344 seconds.
[03/03/2023-12:40:32] [TRT] [I]   Calibrated batch 7 in 1.74846 seconds.
[03/03/2023-12:40:34] [TRT] [I]   Calibrated batch 8 in 1.73344 seconds.
[03/03/2023-12:40:36] [TRT] [I]   Calibrated batch 9 in 1.72423 seconds.
[03/03/2023-12:40:38] [TRT] [I]   Calibrated batch 10 in 1.728 seconds.
[03/03/2023-12:40:39] [TRT] [I]   Calibrated batch 11 in 1.74652 seconds.
[03/03/2023-12:40:41] [TRT] [I]   Calibrated batch 12 in 1.75374 seconds.
[03/03/2023-12:40:43] [TRT] [I]   Calibrated batch 13 in 1.7546 seconds.
[03/03/2023-12:40:45] [TRT] [I]   Calibrated batch 14 in 1.75687 seconds.
[03/03/2023-12:40:47] [TRT] [I]   Calibrated batch 15 in 1.7355 seconds.
[03/03/2023-12:40:54] [TRT] [E] 2: [quantization.cpp::DynamicRange::80] Error Code 2: Internal Error (Assertion min_ <= max_ failed. )

2023-03-03 12:40:54.210 | ERROR    | __main__:<module>:182 - An error has been caught in function '<module>', process 'MainProcess' (469532), thread 'MainThread' (281473415237648):
Traceback (most recent call last):

> File "export.py", line 182, in <module>
    main()
    └ <function main at 0xfffeeae42940>

  File "/opt/ssd/visiontools/edgeyolo/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ ()
           └ <function main at 0xffff0bf304c0>

  File "export.py", line 169, in main
    data_save["model"] = model_trt.state_dict()
    │                    │         └ <function Module.state_dict at 0xffff21304160>
    │                    └ TRTModule()
    └ {'names': ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor'], 'img_siz...

  File "/opt/ssd/visiontools/edgeyolo/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1321, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
                  │    │     │            │       └ {'version': 1}
                  │    │     │            └ ''
                  │    │     └ OrderedDict()
                  │    └ TRTModule()
                  └ <function TRTModule._on_state_dict at 0xfffed7158700>
  File "/opt/ssd/visiontools/edgeyolo/venv/lib/python3.8/site-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/torch2trt.py", line 572, in _on_state_dict
    state_dict[prefix + "engine"] = bytearray(self.engine.serialize())
    │          │                              │    └ None
    │          │                              └ TRTModule()
    │          └ ''
    └ OrderedDict()

AttributeError: 'NoneType' object has no attribute 'serialize'
```

**Comment by LSH9832** [comment]
https://github.com/NVIDIA/TensorRT/issues/1634

**Comment by LSH9832** [comment]
![image](https://user-images.githubusercontent.com/69880398/222714215-3fb6a405-8aad-4f67-8ead-2008c523ee10.png)

**Comment by LSH9832** [comment]
in edgeyolo/export/calib.py, change this function to
```python
class CalibDataset(Dataset):
    def __getitem__(self, item):
        import numpy as np
        ret = []
        for file in self.path_list[item:item + self.batch]:
            im, _ = preproc(cv2.imread(file), self.input_size)
            if self.norm:
                im /= 255.0
            im = np.ascontiguousarray(im, dtype=np.float16)
            ret.append(torch.from_numpy(im).unsqueeze(0).cuda())
        return [torch.cat(ret)]
```

**Comment by LSH9832** [comment]
I don't know whether it is useful because i didn't occur this problem. You can have a try

**Comment by icklerly1** [comment]
Unfortunately the change in the __getitem__ did not help it. 

Do you have another idea?

**Comment by LSH9832** [comment]
maybe change the same version of CUDA、cuDNN and tensorrt as mine?
my enviroment:
```
windows 10
CUDA 11.1
cuDNN 8.0.5
TensorRT 8.2.5.1
```
or
```
ubuntu18.04
CUDA 10.2
cuDNN 7.X(I don't remenber exactly)
TensorRT 7.1.3.0
```
