### ISSUE TITLE
训练好的模型问题

### ISSUE THREAD

**Issue by hanxv1997** [LSH9832/edgeyolo#14]
博主您好，我在使用您的模型对DeepFashion2数据集（采用YOLO格式标签，13个类别，衣服类型）训练后，生成的模型进行正向推理时发生问题，检测框是有的，但是检测框输出的所有类别都是一样的，例如检测框正确框出了“裤子”和“长袖上衣”，但是输出的文字内容均为“短袖”，请问训练自己数据集时，除了修改yaml文件之外还需要修改哪些地方呢？谢谢解答

**Comment by LSH9832** [comment]
按道理是不需要修改别的地方的，方便把模型发给我看看吗 bitshliu@qq.com

**Comment by LSH9832** [comment]
方便加微信聊吗，微信号已发您邮箱

**Comment by sally38ww** [comment]
> 方便加微信聊吗，微信号已发您邮箱

博主您好，我也遇到了一点小问题方便加微信吗，就是我用的是类似voc的数据集，然后修改了两个yaml文件，出现了下面的错误
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    train("DEFAULT" if args.default else args.cfg)
  File "E:\cwh\edgeyolo-main\edgeyolo\train\launch_train.py", line 112, in launch
    train_single(params=params)
  File "E:\cwh\edgeyolo-main\edgeyolo\train\launch_train.py", line 73, in train_single
    trainer.train()
  File "E:\cwh\edgeyolo-main\edgeyolo\train\trainer.py", line 497, in train
    before_train()
  File "E:\cwh\edgeyolo-main\edgeyolo\train\trainer.py", line 337, in before_train
    self.load_init()
  File "E:\cwh\edgeyolo-main\edgeyolo\train\trainer.py", line 273, in load_init
    load_dataloader()
  File "E:\cwh\edgeyolo-main\edgeyolo\train\trainer.py", line 128, in load_dataloader
    save_cache=self.rank == 0
  File "E:\cwh\edgeyolo-main\edgeyolo\data\datasets\get_dataset.py", line 42, in get_dataset
    **cfg["kwargs"]
  File "E:\cwh\edgeyolo-main\edgeyolo\data\datasets\coco.py", line 92, in __init__
    self.load()
  File "E:\cwh\edgeyolo-main\edgeyolo\data\datasets\coco.py", line 121, in load
    self.coco = COCO(self.json_file)
  File "D:\Anaconda3\envs\python37_wt\lib\site-packages\pycocotools\coco.py", line 82, in __init__
    dataset = json.load(f)
  File "D:\Anaconda3\envs\python37_wt\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\Anaconda3\envs\python37_wt\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\python37_wt\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

我是个小白，刚接触这个模型不太会找错误，希望您可以给些意见谢谢博主
