### ISSUE TITLE
cache未保存问题

### ISSUE THREAD

**Issue by Yc1173053907** [LSH9832/edgeyolo#28]
大佬你好，我在你的代码训练部分遇到了问题，可以帮忙解决了吗？
loading VisDrone dataset...
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    train("DEFAULT" if args.default else args.cfg)
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\launch_train.py", line 112, in launch
    train_single(params=params)
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\launch_train.py", line 73, in train_single
    trainer.train()
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\trainer.py", line 497, in train
    before_train()
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\trainer.py", line 337, in before_train
    self.load_init()
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\trainer.py", line 273, in load_init
    load_dataloader()
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\train\trainer.py", line 118, in load_dataloader
    dataset = get_dataset(
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\data\datasets\get_dataset.py", line 37, in get_dataset
    dataset = dataset(
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\data\datasets\visdrone.py", line 89, in __init__
    self.annotation_list = self._load_visdrone_annotations()
  File "D:\soft\study\my_project\yolo_detection\edgeyolo-main\edgeyolo\data\datasets\visdrone.py", line 192, in _load_visdrone_annotations
    with open(cache_file, "wb") as cachef:
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/VisDrone2019-DET/train_cache.edgeyolo'
annotation_list

**Comment by LSH9832** [comment]
这是很早之前下的代码吧，我记得已经修复了，你重新下一遍
